#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p normal

# Load modules
module load eb
module load Miniconda2
module load R

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# ANOSIM statistical test of beta diversity
compare_categories.py \
--method anosim \
-i /home/cbmucl12/cdout_proteobacteria/weighted_unifrac_dm.txt \
-m /home/cbmucl12/map_merged_altered.txt \
-c Year \
-o /home/cbmucl12/anosim_weighted_proteobacteria \
-n 99

source deactivate
