#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 24
#SBATCH -p normal

# Load modules
module load eb
module load Miniconda2
module load R

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# KW statistical test of alpha diversity 
group_significance.py \
-i /home/cbmucl12/summarized_taxa_merged_core_90.biom/merged_otu_table_90_L2.biom \
-m /home/cbmucl12/map_merged_altered.txt \
-c Year \
-s kruskal_wallis \
-o /home/cbmucl12/kw_core_summarized_90.txt

source deactivate
