#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p normal

# Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# Merge OTU tables
merge_otu_tables.py \
-i /home/cbmucl12/2018_02_smb/otu_table_rm_sample.biom,/home/cbmucl12/2017_03_smb/otus_closed_SILVA_2017/otu_table.biom,/home/cbmucl12/2016_02_smb/otus_closed_SILVA_2016/otu_table.biom \
-o /home/cbmucl12/merged_otu_table.biom

source deactivate
