#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p normal

# Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# Merge core OTU tables
merge_otu_tables.py \
-i /home/cbmucl12/2018_02_smb/otu_table_core_2018.biom/core_table_90.biom,/home/cbmucl12/2017_03_smb/otu_table_core_2017.biom/core_table_90.biom,/home/cbmucl12/2016_02_smb/otu_table_core_2016.biom/core_table_90.biom \
-o /home/cbmucl12/merged_otu_table_90.biom

source deactivate
