#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p normal

# Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# Remove samples not in Gordon Square Gardens
filter_samples_from_otu_table.py \
-i /home/cbmucl12/Scripts/otus_closed_SILVA/otu_table.biom \
-o /home/cbmucl12/2018_02_smb/otu_table_rm_sample.biom \
--sample_id_fp /home/cbmucl12/2018_02_smb/id.txt \
--negate_sample_id_fp

source deactivate
