#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 24
#SBATCH -p normal

# Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# Summarising taxanomy at the class level for proteobacteria
summarize_taxa.py \
-i /home/cbmucl12/split_merged_otu_table_90_L2.biom/otu_table_D_0__Bacteria_D_1__Proteobacteria.biom \
-L 3 \
-o /home/cbmucl12/summarized_taxa_merged_core_90_Proteobacteria_L3.biom

source deactivate
